create extension if not exists pgcrypto;

create table if not exists public.invitations (
  id uuid primary key default gen_random_uuid(),
  invitation_name text not null,
  invited_people text[] not null default '{}',
  max_guests integer not null default 1 check (max_guests between 1 and 20),
  token text not null unique default encode(gen_random_bytes(18), 'hex'),
  created_at timestamptz not null default now()
);

create table if not exists public.rsvp_responses (
  id bigint generated by default as identity primary key,
  guest_name text not null,
  party_size integer not null default 1 check (party_size between 0 and 20),
  response text not null check (response in ('oui','non','peut-être')),
  message text not null default '',
  invite_token text not null default '',
  opened_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.invitations enable row level security;
alter table public.rsvp_responses enable row level security;

drop policy if exists "public can insert rsvp" on public.rsvp_responses;
create policy "public can insert rsvp" on public.rsvp_responses for insert to anon, authenticated with check (true);

drop policy if exists "authenticated can read rsvp" on public.rsvp_responses;
create policy "authenticated can read rsvp" on public.rsvp_responses for select to authenticated using (true);

create or replace function public.get_invitation_by_token(p_token text)
returns table (invitation_name text, invited_people text[], max_guests integer)
language sql
security definer
set search_path = public
as $$
  select i.invitation_name, i.invited_people, i.max_guests
  from public.invitations i
  where i.token = p_token
  limit 1;
$$;

revoke all on function public.get_invitation_by_token(text) from public;
grant execute on function public.get_invitation_by_token(text) to anon, authenticated;
